name: Anime
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=1.1.1w
  - pip=25.3
  - python=3.11.0
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.12.0
      - black==25.12.0
      - blinker==1.9.0
      - certifi==2025.11.12
      - click==8.3.1
      - colorama==0.4.6
      - distro==1.9.0
      - dotenv==0.9.9
      - filelock==3.20.1
      - flask==3.1.2
      - flask-cors==6.0.2
      - fsspec==2025.12.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - interchange==2021.0.4
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.3
      - markupsafe==3.0.3
      - monotonic==1.6
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - neo4j==6.0.3
      - networkx==3.6.1
      - numpy==2.4.0
      - openai==2.14.0
      - packaging==25.0
      - pansi==2024.11.0
      - pathspec==0.12.1
      - pillow==12.0.0
      - platformdirs==4.5.1
      - py2neo==2021.2.4
      - pyahocorasick==2.3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - python-dotenv==1.2.1
      - pytokens==0.3.0
      - pytz==2025.2
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.9.1
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.2
      - werkzeug==3.1.4
prefix: D:\miniconda3\envs\Anime
